# Generated by Django 3.2.11 on 2024-06-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProchainConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spectacle')),
            ],
        ),
    ]
