# Generated by Django 3.2.11 on 2024-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240628_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeqr',
            name='code_secret',
            field=models.CharField(default=' ', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeqr',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codeqr',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
