# Generated by Django 3.2.11 on 2024-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='lien_streaming',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DetailsSpectacle',
        ),
    ]
