# Generated by Django 5.0.6 on 2024-07-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240705_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prochainconcert',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='prochainconcert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('statut_paiement', models.CharField(max_length=20)),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spectacle')),
            ],
        ),
    ]
